# registry.gitlab.com/jorjpimm/dockerfiles/build.gcc7

FROM registry.gitlab.com/jorjpimm/dockerfiles/build.gcc7.ui

ADD install_ui_dependencies.sh /install_ui_dependencies.sh
#RUN chmod +x /install_ui_dependencies.sh && /install_ui_dependencies.sh