# registry.gitlab.com/jorjpimm/dockerfiles/build.gcc7

FROM registry.gitlab.com/jorjpimm/dockerfiles/build.base

RUN apt install -y software-properties-common ; \
    add-apt-repository -y ppa:ubuntu-toolchain-r/test ; \
    apt update ; \
    apt install -y gcc-7 g++-7 ; \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 \
        --slave /usr/bin/g++ g++ /usr/bin/g++-7
